### ISSUE TITLE
enabling hhvm.php7.all casues fatal error

### ISSUE THREAD

**Issue by ghost** [alex-phillips/clouddrive-php#22]
not sure if I should pass this on to guzzle?

```
#0 /usr/share/php/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php(67): GuzzleHttp\Exception\RequestException::wrapException()
#1 /usr/share/php/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(52): GuzzleHttp\Handler\StreamHandler->__invoke()
#2 /usr/share/php/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(42): Closure$GuzzleHttp\Handler\Proxy::wrapStreaming()
#3 /usr/share/php/vendor/guzzlehttp/guzzle/src/Middleware.php(30): GuzzleHttp\PrepareBodyMiddleware->__invoke()
#4 /usr/share/php/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(68): Closure$GuzzleHttp\Middleware::cookies#2()
#5 /usr/share/php/vendor/guzzlehttp/guzzle/src/Middleware.php(57): GuzzleHttp\RedirectMiddleware->__invoke()
#6 /usr/share/php/vendor/guzzlehttp/guzzle/src/HandlerStack.php(67): Closure$GuzzleHttp\Middleware::httpErrors#2()
#7 /usr/share/php/vendor/guzzlehttp/guzzle/src/Client.php(268): GuzzleHttp\HandlerStack->__invoke()
#8 /usr/share/php/vendor/guzzlehttp/guzzle/src/Client.php(123): GuzzleHttp\Client->transfer()
#9 /usr/share/php/vendor/guzzlehttp/guzzle/src/Client.php(129): GuzzleHttp\Client->requestAsync()
#10 /usr/share/php/vendor/guzzlehttp/guzzle/src/Client.php(87): GuzzleHttp\Client->request()
#11 /usr/share/php/vendor/alex-phillips/clouddrive/src/CloudDrive/CloudDrive.php(236): GuzzleHttp\Client->__call()
#12 ...: CloudDrive\CloudDrive->downloadFile()
#13 {main}

```

**Comment by alex-phillips** [comment]
That would probably be best. I'm not changing with their code, just using it.

**Comment by ghost** [comment]
it is caused by the `stream` option, I have replied to the guzzle hhvm open issue.
Disabling it does not give any problems. I guess it could give problems for quite large files?

**Comment by alex-phillips** [comment]
If you attempt to download a large file without using a stream, the contents of the file will be loaded into memory. This probably isn't a problem for small files, but if the file is big enough then the PHP process itself will run out of memory and fatal.
